### ISSUE TITLE
Auth Scaffolding Hangup

### ISSUE THREAD

**Issue by mdean400** [rustymulvaney/bulma#5]
After running php artisan bulma:install with Auth Scaffolding on, the package outputs the following, and then hangs up:

Progress: [=====>----------------------] Installing Node modulesProgress: [>---------------------------] Installing dependencies
Progress: [=====>----------------------] Generating auth scaffolding

**Comment by 1415926535** [comment]
I'm getting the exact same behavior. Just tried on fresh Laravel install and got a passport not found error. 

> FatalErrorException 'Laravel\Passport\HasApiTokens' not found

![2017-08-03_956x570](https://user-images.githubusercontent.com/15851161/28948615-d9268f62-7884-11e7-91e2-dfbf80115acd.png)

Ubu 16.04
zsh
5 GBs of memory available

**Comment by 1415926535** [comment]
I got more info this time. This time I ran it on Homestead so the DB was setup and accessible if needed. 

Progress: [=====>----------------------] Installing Node modulesProgress: [>---------------------------] Installing dependencies
Progress: [=====>----------------------] Generating auth scaffoldingPHP Fatal error:  Trait **'Laravel\Passport\HasApiTokens' not found in /home/vagrant/code/larbull/app/User.php on line 11**

![2017-08-03-205456_1100x539_scrot](https://user-images.githubusercontent.com/15851161/28950029-c065ec7a-788e-11e7-87c3-4f857cd95173.png)

**Comment by 1415926535** [comment]
It's referring to LINE 11 but I don't know what is wrong with it. 
![2017-08-03-210336_518x540_scrot](https://user-images.githubusercontent.com/15851161/28950115-545624a4-788f-11e7-920f-293e5a2804f3.png)

**Comment by 1415926535** [comment]
From what I can tell mine works even though it borked.

**Comment by 1415926535** [comment]
I was digging in the code on [src/Commands/InstallCommand.php](https://github.com/rustymulvaney/bulma/blob/master/src/Commands/InstallCommand.php) and my install did not complete. 

Looking at the last time this repo was modified I think this was built for 5.3 but not sure. I'm new to dev world.

**Comment by mccheesy** [comment]
The issue is that in Laravel 5.4, the default auth scaffolding is built-in in new projects. So, when the install command tries to run "php artisan make:auth" silently, it freezes while it waits for the user to respond to queries about replacing the existing files.

Comment out line 99 "$this->callSilent('make:auth');" and the script should run just fine.

**Comment by 1415926535** [comment]
Thanks. I was just exploring code so not sure I'll attempt again. A wee bit swamped at the moment.
